### ISSUE TITLE
Error compile on Mac OS X

### ISSUE THREAD

**Issue by tetratec** [plushmonkey/mclib#10]
MacBook-Pro-Packet:mclib-master Packet$ make
clang++ -std=c++14 -fPIC -O2 -I./mclib/include -I./lib/utf8/include -I./lib/jsoncpp/include   -c -o mclib/src/mclib/core/Connection.o mclib/src/mclib/core/Connection.cpp
mclib/src/mclib/core/Connection.cpp:257:12: error: no matching function for call
      to 'async'
    return std::async(std::launch::async, &protocol::packets::PacketFact...
           ^~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:2357:1: note: 
      candidate template ignored: substitution failure [with _Fp =
      mc::protocol::packets::Packet *(*)(mc::protocol::Protocol &,
      mc::protocol::State, mc::DataBuffer, unsigned long, mc::core::Connection
      *), _Args = <mc::protocol::Protocol &, mc::protocol::State &,
      mc::DataBuffer &, int, mc::core::Connection *>]: no type named 'type' in
      'std::__1::__invoke_of<mc::protocol::packets::Packet
      *(*)(mc::protocol::Protocol &, mc::protocol::State, mc::DataBuffer,
      unsigned long, mc::core::Connection *), mc::protocol::Protocol,
      mc::protocol::State, mc::DataBuffer, int, mc::core::Connection *>'
async(launch __policy, _Fp&& __f, _Args&&... __args)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:2383:1: note: 
      candidate template ignored: substitution failure [with _Fp =
      std::__1::launch, _Args = <mc::protocol::packets::Packet
      *(*)(mc::protocol::Protocol &, mc::protocol::State, mc::DataBuffer,
      unsigned long, mc::core::Connection *), mc::protocol::Protocol &,
      mc::protocol::State &, mc::DataBuffer &, int, mc::core::Connection *>]: no
      type named 'type' in 'std::__1::__invoke_of<std::__1::launch,
      mc::protocol::packets::Packet *(*)(mc::protocol::Protocol &,
      mc::protocol::State, mc::DataBuffer, unsigned long, mc::core::Connection
      *), mc::protocol::Protocol, mc::protocol::State, mc::DataBuffer, int,
      mc::core::Connection *>'
async(_Fp&& __f, _Args&&... __args)
^

**Comment by daemon** [comment]
need to fix or else i'll need to install windows 10 on my macbook
