### ISSUE TITLE
[Help Please] Building client doesn't work

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [plushmonkey/mclib#13]
I'm using Windows 10. I downloaded the zipped file and unzipped it. I opened it in Visual Studio and went to client -> Source Files -> main.cpp and tried to run it. There were a lot of errors:
https://gyazo.com/e7a41da5adb622ea80e8ecac4bd28d23

What am I doing wrong? Please note: I took a class in basics of C++ but other than that I have no experience in it. I'd like to learn how to create my own bots in C++ (along with testing yours) but there are no tutorials for this kind of thing so I'm trying to learn it myself. In other words, please be patient with me. :P 

Thanks!

**Comment by plushmonkey** [comment]
You need to unzip the lib.zip file that's included.

**Comment by PiggiesGoSqueal** [comment]
Thanks for replying, I'm surprised you still check this project based off when it was last updated. :P

I just tried what you said but now it tells me:
The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".

So I downloaded it (just in case I didn't already have it) and I still get that message. Then I tried closing the project and re-opening it just in case and still get that error.

Just in case I'm missing something, this is my control panel's list of installed programs:
https://gyazo.com/3d0ebe772ae24aaeab2ac764de395152

Any idea how to fix? :/

**Edit:** I tried the "Retarget Solution" option it said in the error and it started building it but said these error msgs:
2>LINK : fatal error LNK1104: cannot open file 'mclibd.lib'
2>Done building project "tests.vcxproj" -- FAILED.
1>c:\users\tommy\downloads\mclib-master\mclib\src\mclib\core\authtoken.cpp(85): warning C4101: 'e': unreferenced local variable

Then when it finished loading, those errors disappeared and it showed these errors:
https://gyazo.com/4766c27b2aea597f03ff93b0ac896a55 :/

**Comment by PiggiesGoSqueal** [comment]
@plushmonkey I'd like to re-open this. ^

Sorry for the late reply.

**Comment by plushmonkey** [comment]
I didn't want to reopen this because I don't think it's an issue with the project.

It looks like I forgot to set mclib as a build dependency for the tests project. This isn't a huge issue since the tests project isn't required, and it can be fixed by just building the mclib project first. 

You only need to build the mclib project that's included in the solution to get the mclib.lib and mclib.dll files that you can use for your own projects. I would recommend building the release versions of them.

You can ignore all of the PDB warnings.

**Comment by PiggiesGoSqueal** [comment]
Okay, thank you.
